### PR TITLE
Add style group fn, use a face for annote fn

### PR DESCRIPTION
**Pull request by bdarcus**
This isn't finished, and you're code is changing too fast to keep up, but if you're interested, it's a good start.

Two changes for styles select UI:

1. use a face for the annotation (though I didn't include that face here)
2. add a `group-function`, as with the one I created for `bibtex-actions`; will work beautifully in Emacs 28, and degrade gracefully in earlier versions.

I'll just open as a draft.

### CODE REVIEW

**Comment by jkitchin** [comment]
where does that go for completing-read?

**Comment by bdarcus** [comment]
Here's my function:

```elisp
(defun oc-bibtex-actions-select-style ()
"Complete a citation style for org-cite with preview."
  (interactive)
  (let* ((oc-styles (oc-bibtex-actions--styles-candidates))
         (style
          (completing-read
           "Styles: "
           (lambda (str pred action)
             (if (eq action 'metadata)
                 `(metadata
                   (annotation-function . oc-bibtex-actions--style-preview-annote)
                   (cycle-sort-function . identity)
                   (display-sort-function . identity)
                   (group-function . oc-bibtex-actions--styles-group-fn))
               (complete-with-action action oc-styles str pred)))))
         (style-final (string-trim style)))
    (if (string= style-final "/") "" style-final)))
```

So exactly the same as hooking up the annotation-function. 

It's just (and I did report this to someone working on this stuff) the convenience function you use (`additional-properties` or some such) doesn't currently appear to include group functions as an option. That may just be because it's newer.

**Comment by bdarcus** [comment]
BTW, in my experiments here, I decided to use long style names and short variants. I think that's a good balance.

**Comment by jkitchin** [comment]
cool, thanks for the examples. See b95cb05, I implemented a compatible version with bibtex-completion-candidates.

emacs 28 seems to break a lot of packages though, so I wouldn't make this default for a while.

**Comment by jkitchin** [comment]
I couldn't figure out how to use the grouping though, I thought based on your example that

```
(lambda (key transform)
							 (if transform
							     key
							   (substring s 0 1)))
```

would group them alphabetically. It didn't seem to that though.

**Comment by bdarcus** [comment]
> emacs 28 seems to break a lot of packages though, so I wouldn't make this default for a while.

I think it's pretty unlikely either would cause problems, unless you made UI assumptions about them being present.

- `annotation-function` = Emacs 27 (28 has a generalization of this currently called affixation)
- `group-function` = Emacs 28

But Emacs 26, for example, will just ignore those functions.

As in, you'll just get the list of styles in older versions.

> I couldn't figure out how to use the grouping though, I thought based on your example that ... would group them alphabetically.

I'm not myself certain how sorting and grouping interact.

Maybe you need to use the `display-sort-function` for that?

I used "identity" because I didn't want resorting from what I had in the alist.

But I didn't experiment with it beyond that.

**Comment by jkitchin** [comment]
it isn't completing read that is the problem, it is this one: https://github.com/hlissner/doom-emacs/issues/4534

in the version of 28 I installed with brew, I can't even load my init file without some major hackery to solve that problem.

**Comment by bdarcus** [comment]
I guess I'm missing something, but how does that relate to your function?

BTW, I get an error when trying to run it from IELM:

```elisp
ELISP> (org-ref-cite--complete-key-28)
*** Eval error ***  Symbol’s value as variable is void: key
```

**Comment by jkitchin** [comment]
that is my bad. I think I fixed it in 7512e24.

**Comment by bdarcus** [comment]
You have another little variable bug in the group function. If you change `s` to `key`, this is the result, in Vertico:

image

**Comment by jkitchin** [comment]
> I guess I'm missing something, but how does that relate to your function?
> 
When emacs doesn't load, I can't run my function. Apparently emacs 28 changed some function signatures that a lot of packages have not adapted to yet.

**Comment by jkitchin** [comment]
> You have another little variable bug in the group function. If you change `s` to `key`, this is the result, in Vertico:
> 
> image

Nice catch, thanks! I found a few more issues with my strings that are handled now.

**Comment by bdarcus** [comment]
I added a note about org-ref-cite and details on how to configure pieces of it with this commit.

https://github.com/bdarcus/bibtex-actions/commit/4c6aa3612da91e9de27687bb2a7aeb4999ca84f5

Maybe you can include a similar suggestion to look at bibtex-actions for the selectrum/vertico/embark users out there?

I've had a lot more time to polish `bibtex-actions-read` ;-)

**Comment by jkitchin** [comment]
I did add some notes pointing to your bibtex-actions repo, and an example of mixing and matching.

**Comment by bdarcus** [comment]
Cool; thanks.

**Pull request closed without merging**
